#DataSouce Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 外网访问测试数据地址
    url: jdbc:mysql://39.106.10.15:3306/newhand_db?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    #内网访问测试数据库地址
    #url: jdbc:mysql://192.168.31.151:3306/db_newhand?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: newhand
    password: 1RKhGzknMJ
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

# Secret Key Configuration
newhand:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长：7天 单位： 秒
    expire: 604800
    header: token
# Shiro-Redis Configuration
shiro-redis:
  enabled: true
  redis-manager:
    # 虚拟机Redis
    host: 192.168.133.7:6379
    #host: 127.0.0.1:6379

server:
  port: 8081